// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB80FXOIEZ7OJkjhQbze71PdLq2C5AcgXk',
    appId: '1:363721080567:web:b5dc1466621161cd0e1df2',
    messagingSenderId: '363721080567',
    projectId: 'chat-and-noti',
    authDomain: 'chat-and-noti.firebaseapp.com',
    storageBucket: 'chat-and-noti.firebasestorage.app',
    measurementId: 'G-E8TF267CP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAglkF4THj-ySGOjjSS4yMuLSAPTJFh6sk',
    appId: '1:363721080567:android:c21d01ecd2e993fe0e1df2',
    messagingSenderId: '363721080567',
    projectId: 'chat-and-noti',
    storageBucket: 'chat-and-noti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYjtwENmk3FdDZChRUW2jZdhv9t0D_yBo',
    appId: '1:363721080567:ios:4f3d734935bcccd00e1df2',
    messagingSenderId: '363721080567',
    projectId: 'chat-and-noti',
    storageBucket: 'chat-and-noti.firebasestorage.app',
    iosBundleId: 'com.example.chatAndNoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYjtwENmk3FdDZChRUW2jZdhv9t0D_yBo',
    appId: '1:363721080567:ios:4f3d734935bcccd00e1df2',
    messagingSenderId: '363721080567',
    projectId: 'chat-and-noti',
    storageBucket: 'chat-and-noti.firebasestorage.app',
    iosBundleId: 'com.example.chatAndNoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB80FXOIEZ7OJkjhQbze71PdLq2C5AcgXk',
    appId: '1:363721080567:web:7808ab1128d4f6130e1df2',
    messagingSenderId: '363721080567',
    projectId: 'chat-and-noti',
    authDomain: 'chat-and-noti.firebaseapp.com',
    storageBucket: 'chat-and-noti.firebasestorage.app',
    measurementId: 'G-ERJN38VB8N',
  );
}
